name: Deploy Next App
on:
  push:
    branches: [live]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Pulling & Restarting
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_USERNAME }}
        password: ${{ secrets.REMOTE_PASSWORD }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script_stop: true
        script: |
          cd next-sukadia.dev
          git stash
          git stash drop || true
          git pull origin live
          npm i
          pm2 restart sukadia.dev